### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by imlautaro** [supabase/nuxt-supabase#1]
# Bug report

After setup the module using npm I have an error that says "Cannot use import statement outside a module.

## To Reproduce

Clone [this project](https://github.com/imlautaro/nuxt-supabase-issue) and follow the instructions provided in the README of the repo.

## Expected behavior

That the module works 😆

## Screenshots

![image](https://user-images.githubusercontent.com/54757902/114245543-105acf00-9967-11eb-8dfd-0f4acb10d6a1.png)

## System information

- OS: Windows (I test it using PowerShell & Debian WSL)
- Version of supabase-js: 1.9.0
- Version of Node.js: 15.13.0
- Version of NPM: 7.8.0

**Comment by scottrobertson** [comment]
So it looks like it's when `ssr: true` (the default) this fails. Having never used SSR, I will need to do some digging into how this works, and why it's erroring like this.

**Comment by imlautaro** [comment]
If you don't know much about NuxtJS let me take care of the module to me. I made a module that works very well and has TypeScript integration. If you want, take a look at the [repository](https://github.com/nuxtclub/supabase).

**Comment by charlie17** [comment]
Faced the same problem, after adding `ssr: false` to `nuxt.config.js`, works as expected. Not sure if this might cause problems in other parts of my Nuxt app though

**Comment by scottrobertson** [comment]
> Faced the same problem, after adding `ssr: false` to `nuxt.config.js`, works as expected. Not sure if this might cause problems in other parts of my Nuxt app though

Yeah, 100% not a fix we can ask people to do. Will look into it as soon as I get some time.

**Comment by phiberber** [comment]
Seems that someone already found a fix to this issue, is that valid? Didn't test yet and probably won't as I have zero experience with Nuxt Modules.
 
https://github.com/asyncapi/asyncapi-react/issues/177#issuecomment-831905940

**Comment by scottrobertson** [comment]
This should be resolved now. Let me know if you have any issues. Shall publish a new version soon.
