### ISSUE TITLE
Add environment variables example

### ISSUE THREAD

**Issue by florian-lefebvre** [supabase/nuxt-supabase#10]
# Improve documentation

## Describe the problem

Storing sensitive data in environment variables is better for security reasons. However, Nuxt approach concerning those variables is not easy to understand.

## Describe the improvement

Add an example with the `supabaseUrl` and `supabaseKey` using environment variables.

## Additional context

Depending on the version of Nuxt, there are 3 different ways of doing that: `env`, `publicRuntimeConfig` or `privateRuntimeConfig`.

**Comment by sduduzog** [comment]
I feel like this is mostly tied to Nuxt more so than this module. However you structure your `nuxt.config.js` pretty much decides everything else. i.e. hard coding such properties or have them as .env variables. Or maybe I'm not understanding this issue well

**Comment by florian-lefebvre** [comment]
Yes you're right. I'm personnaly struggling with it, how would you retrieve the supabaseKey from an `.env` file to use it directly in `nuxt.config.js` ?

**Comment by sduduzog** [comment]
In my case, I have, in my `.env` file
SUPABASE_URL=...
SUPABASE_KEY=...

and nuxt automatically picks it up so in my nuxt.config.js file:
```js
['nuxt-supabase', {
    supabaseUrl: process.env.SUPABASE_URL,
    supabaseKey: process.env.SUPABASE_KEY
  }]
```
And I'm all set

**Comment by titogarrido** [comment]
Hi @sduduzog could you explain how do you use these variables inside the "plugins" folder?

I am struggling to read then from `plugins/supabase.client.js`

This is my plugin file:
```
/* plugins/supabase.client.js */
import { createClient } from '@supabase/supabase-js'
const supabase = createClient(
  $config.SUPABASE_HOST,
  $config.SUPABASE_SECRET
)
export default (_, inject) => {
  inject('supabase', supabase)
}
```

This is my nuxt.config.js:
```
  publicRuntimeConfig: {
    SUPABASE_HOST: process.env.SUPABASE_HOST,
  },

  privateRuntimeConfig: {
    SUPABASE_SECRET: process.env.SUPABASE_SECRET
  },
```

How can I fetch them from the plugin folder?

Thanks!

**Comment by titogarrido** [comment]
My bad! I wasn't using the nuxt-supabase module... It works as @sduduzog described now.

Thanks!

**Comment by sduduzog** [comment]
Awesome. @titogarrido I'm glad you figured it out 👍🏼
