### ISSUE TITLE
TS2339: Property '$supabase' does not exist on type 'x'. - nuxt-property-decorator

### ISSUE THREAD

**Issue by jannikbuscha** [supabase/nuxt-supabase#11]
# Bug report - TS2339: Property '$supabase' does not exist on type 'x'. - nuxt-property-decorator

## Description

Hello, I already reported this error on the last pull request, it's still the error I get when I use the whole thing with the functions from nuxt-property-decorator:

![image](https://user-images.githubusercontent.com/74017697/131023763-192ad934-dddc-4200-8120-e8668bbc48d8.png)

The funny thing is that everything works though:

![image](https://user-images.githubusercontent.com/74017697/131024556-53013027-bf10-41a1-ae55-fba0c3fdc304.png)

Here the complete code:

![image](https://user-images.githubusercontent.com/74017697/131024693-a1f274f3-5478-4e4e-97ee-f1f1dbe32521.png)

Also added a ts-shim.d.ts and types

![image](https://user-images.githubusercontent.com/74017697/131024763-30bc234f-9754-4961-b056-acee57625760.png)

![image](https://user-images.githubusercontent.com/74017697/131024821-d4d35d25-1933-47b1-b6b6-04cc37d44586.png)

Are there perhaps other ways I can set this up?

## System information

- OS: Windows
- Browser: Chromium
- Version of supabase-js: ^2.0.0
- Version of Node.js: v14.17.4.
- Version of nuxt-property-decorator: ^2.9.1
- IDE: PhpStorm 2021.2

**Comment by sduduzog** [comment]
@scottrobertson I noticed that master is ahead of the latest release. The fix for this is actually there. 

@jannikbuscha If you're still unsure about this, please install this module from github to try out the fix i.e. `npm install supabase/nuxt-supabase` and see that the typescript error message dissapears.

@scottrobertson This could be solved by a patch release I believe

**Comment by scottrobertson** [comment]
> @scottrobertson I noticed that master is ahead of the latest release. The fix for this is actually there. 
> 
> 
> 
> @jannikbuscha If you're still unsure about this, please install this module from github to try out the fix i.e. `npm install supabase/nuxt-supabase` and see that the typescript error message dissapears.
> 
> 
> 
> @scottrobertson This could be solved by a patch release I believe

Hey

Sorry, out this week. 

@kiwicopple could you perhaps make @sduduzog a contributor so they can do releases here and the other repo?

@sduduzog once you have access, just bump the version number in package.json and then go to the draft release in GitHub and publish it.

**Comment by sduduzog** [comment]
It's worth mentioning @jannikbuscha 

If you want to get this working in the meantime before the release, add this snippet to your projects types file
```typescript
import { SupabaseClient } from '@supabase/supabase-js';

declare module 'vue/types/vue' {
interface Vue {
  $supabase: SupabaseClient;
}
```

or create a `nuxt-supabase.d.ts` file to the root of your project and add the snippet there i.e.
![image](https://user-images.githubusercontent.com/48126337/132551118-fed7f36b-9c40-467f-b440-4fc27fab7c26.png)

and this should get you sorted until it's part of the release
