### ISSUE TITLE
nuxt-supabase should depend on vue-supabase and not supabase-js

### ISSUE THREAD

**Issue by sduduzog** [supabase/nuxt-supabase#3]
# Feature request

## Is your feature request related to a problem? Please describe.
Currently there's no big problem but this would remove some inconvenience when maintaining both the repositories.

A clear and concise description of what you want and what your use case is.
When vue-supabase is setup to support both Vue2 and Vue3 there wont be any work needed to be done this side apart from a version bump. So will be the case for any feature that will be added to vue-supabase and any issues raised will most likely need to be solved in one place than 2.

## Describe the solution you'd like
nuxt-supabase should just have vue-supabase as a dependency and it should use it underneath to setup the module

## Describe alternatives you've considered
None so far

## Additional context
I'm also happy to give this a shot, worst case scenario is this issue being picked up and fixed by anyone else in the community should you not have any time to look into it.

**Comment by scottrobertson** [comment]
It actually used to, but I removed it due to https://github.com/supabase/nuxt-supabase/issues/1

Feel free to have a go at getting it to work though :)

**Comment by sduduzog** [comment]
I forgot to add a "closes" on my commits 🤣

**Comment by sduduzog** [comment]
For reference, closed by https://github.com/supabase/nuxt-supabase/pull/4
